apiVersion: v1
kind: Service
metadata:
  name: k8s-helloworld
spec:
  selector:
    app: helloworld
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld
  labels:
    app: helloworld
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - name: server
        image: IMAGE:TAG
        env:
        - name: PORT
          value: '8080'
        ports:
        - containerPort: 8080
          protocol: TCP
          name: server
  volumes:
  - name: k8s-helloworld-configmap
    configMap:
      name: k8s-helloworld-configmap

