name: Docker

on:
  push:

jobs:
  buildx:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      matrix:
        python-version: [3.9]
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      # with:
      #   submodules: true
      #   lfs: true
      #   token: ${{ secrets.GH_USER_SWAG_BOT }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f webapp/requirements.txt ]; then pip install -r webapp/requirements.txt; fi

    - name: Test with pytest
      run: |
        pytest webapp/tests.py

    - name: Setup
      id: config
      run: |
        NPROC=$(nproc)

        echo "NPROC=$NPROC" >> $GITHUB_ENV
        echo "::set-output name=NPROC::$NPROC"

        [[ $GITHUB_REF =~ ^refs\/(tags\/|heads\/(master|release|hotfix)$) ]] && echo "::set-output name=push-to-registry::true" || true

    - name: Setup - buildx
      uses: docker/setup-buildx-action@v1

    # - name: Setup - Google Artifact Registry
    #   uses: docker/login-action@v1
    #   if: ${{ steps.config.outputs.push-to-registry }}
    #   with:
    #     registry: asia-docker.pkg.dev
    #     username: _json_key
    #     password: ${{ secrets.GOOGLE_SA_GCR_JSON }}

    - name: Setup - Heroku Container Registry
      uses: docker/login-action@v1
      if: ${{ steps.config.outputs.push-to-registry }}
      with:
        registry: registry.heroku.com
        username: _
        password: ${{ secrets.HEROKU_REGISTRY_TOKEN }}

    - name: Setup - Github Container Registry
      uses: docker/login-action@v1
      if: ${{ steps.config.outputs.push-to-registry }}
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup - Dockerhub Container Registry
      uses: docker/login-action@v1
      if: ${{ steps.config.outputs.push-to-registry }}
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}


    - name: Setup - Docker image metadata
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: |
          ${{ github.repository }}
          ghcr.io/${{ github.repository }}
          registry.heroku.com/evening-reaches-68081/web
        tags: |
          type=ref,event=branch
          type=ref,event=tag
          type=sha
          type=raw,value=latest

    - name: Build
      uses: docker/build-push-action@v2
      with:
        context: .
        push: ${{ steps.config.outputs.push-to-registry == 'true' }}
        labels: ${{ steps.meta.outputs.labels }}
        tags: ${{ steps.meta.outputs.tags }}
        # build-args: |
        #   MAKEFLAGS=-j${{ env.NPROC }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
